image: Visual Studio 2015

stack: node 10

branches:
  only:
    - master

cache: node_modules

install:
  - npm install

build: off

build_script:
  - npm run build

test_script:
  - npm run lint && npm test
